---
title: "project 3"
author: "Mu-Tien, Lee"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("plotly")
#install_github("vqv/ggbiplot")
library(ggbiplot)
library(remotes)
library(dmm)
library(knitr)
library(rmarkdown)
library(MuMIn)
library(tidyverse)
library(caret)
library(corrplot)
library(readxl)
library(caret)
library(ggiraphExtra)
library(knitr)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(rpart.plot)
library(rpart)
library(DT)
```

```{r data}
data <- read.csv("./diabetes_data.csv")
for( j in 1: nrow(data)){    
  ifelse (data[j,17] == "Positive", data[j,17] <- 1,data[j,17] <- 0)

  for (i in 3:16){
    if (data[j,i] == "Yes") data[j,i] <- 1
    else if (data[j,i] == "No") data[j,i] <- 0
    }
} 
mydata<- data
for (i in 3:16){
  mydata[,i] <- as.numeric(mydata[,i])%>% as.factor()
  data[,i] <- as.numeric(data[,i])
}
data <- as_tibble(data)
mydata$class <- as.factor(mydata$class)
mydata <- as_tibble(mydata)
```

#plot
```{r plot data}
#histogram
ggplot(data=mydata, aes(x=Age))+geom_histogram(aes(fill=class))+labs(title = "Histogram for age seperate by test result")+facet_grid(.~Gender)+scale_fill_discrete(name="Test result", labels=c("Negative", "Positive"))

dataplot <- function(var1, var2){
  t <- paste0("Scatter plots for ", var1, " and ", var2)
  ggplot(data=mydata)+geom_jitter(aes_string(x=var1, y=var2, color="class"))+facet_grid(.~Gender)+labs(title = t)+ scale_fill_discrete(name="Test result", labels=c("Negative", "Positive"))
}
dataplot("Polyuria","Polyphagia")
# legent incorrect
names(mydata)
```
#summary table
```{r table}
sumtable <- function(groups, ...){
  sumdata <- data %>% group_by(Gender, class)
  sumdata <-sumdata %>% summarise_all(list(mean))
  datatable(sumdata)
}
sumtable(groups=c("Gender","class"))
```

#unsupervised learning
```{r PCA}
install.packages("ggbiplot")
library(ggbiplot)
for (i in 1:nrow(data)){
  ifelse(data[i,2]=="Male",data[i,2] <- "1", data[i,2]<-"0" )
}
data$Gender <- as.numeric(data$Gender)
pairs(data[,1:16],cex=0.4)
PCs <- prcomp(data[,1:16], center=TRUE, scale=TRUE)
screeplot(PCs, type = "lines")
biplot(PCs, xlabs=data$class, choices = c(1,2))
ggbiplot(PCs, group=data$class)
```

```{r Clustering}
#install.packages("factoextra")
#install.packages("cluster")
#install.packages("magrittr")
#install.packages("NbClust")
library("cluster")
library("factoextra")
library("magrittr")
library("NbClust")
#k-mean
fviz_nbclust(data[,1:16], kmeans, method = "silhouette")
set.seed(123)
km.res <- kmeans(data[,1:16], 3)
fviz_cluster(km.res, data = data[,1:16],
             ellipse.type = "convex",
             palette = "jco")

{(1.96+1.96*√(12/60))/12}^2*4*12#Hierarchical 
HierClust <- hclust(dist(data.frame(data[,1:16])), method = "ward.D2")
fviz_dend(HierClust, k = 4, # Cut in four groups
          cex = 0.5, # label size
          palette = "jco",
          show_labels = FALSE, # color labels by groups
          rect = TRUE # Add rectangle around groups
          )
```

# supervised learning
```{r}
set.seed(615)
train <- sample(1:nrow(mydata), size = nrow(mydata)*0.8)
test <- dplyr::setdiff(1:nrow(mydata), train)
diabetesdataTrain <- diabetesdata[train, ]
diabetesdataTest <- diabetesdata[test, ]

```

